# Generated by Django 2.1.5 on 2019-01-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190127_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='labels',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_height',
            field=models.IntegerField(blank=True, default=1600),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_width',
            field=models.IntegerField(blank=True, default=1600),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
