# Generated by Django 2.1.5 on 2019-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190127_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='labels',
            field=models.ManyToManyField(blank=True, to='music.Label'),
        ),
    ]
