# Generated by Django 2.1.5 on 2019-01-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190127_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='album',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.AddField(
            model_name='artist',
            name='image_height',
            field=models.IntegerField(blank=True, default=1600),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_width',
            field=models.IntegerField(blank=True, default=1600),
        ),
        migrations.AddField(
            model_name='genre',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='genres', to='music.Album'),
        ),
        migrations.AddField(
            model_name='label',
            name='album',
            field=models.ManyToManyField(related_name='labels', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, height_field='image_width', upload_to='artist_imgs', width_field='image_height'),
        ),
    ]
