# Generated by Django 2.1.5 on 2019-01-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190127_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='albums', to='music.Label'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.Label'),
        ),
    ]
