# Generated by Django 2.1.5 on 2019-01-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20190127_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='label',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
