# Generated by Django 2.1.5 on 2019-01-29 16:10

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190127_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='label',
            name='id',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
