# Generated by Django 2.1.5 on 2019-02-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20190129_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, height_field='cover_height', upload_to='music/', width_field='cover_width'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, height_field='image_width', upload_to='music/', width_field='image_height'),
        ),
    ]
