# Generated by Django 2.1.5 on 2019-01-28 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('image_width', models.IntegerField(blank=True, default=1600)),
                ('image_height', models.IntegerField(blank=True, default=1600)),
                ('image', models.ImageField(blank=True, height_field='image_width', upload_to='artist_imgs', width_field='image_height')),
                ('standfirst', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
