# Generated by Django 2.1.5 on 2019-01-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default='', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
