# Generated by Django 2.1.5 on 2019-01-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190129_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default='KYGAx0x', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
