# Generated by Django 2.1.5 on 2019-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190129_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default='mkyfdYs0', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
