# Generated by Django 2.1.5 on 2019-02-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190129_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='carousel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='top_story',
            field=models.BooleanField(default=False),
        ),
    ]
