# Generated by Django 2.1.11 on 2019-09-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190209_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='carousel',
            new_name='frontpage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='top_story',
        ),
    ]
