# Generated by Django 2.1.5 on 2019-01-27 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190127_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='authors',
            field=models.ManyToManyField(related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
