# Generated by Django 2.1.5 on 2019-01-27 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190127_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
    ]
