# Generated by Django 2.1.5 on 2019-01-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190127_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='standfirst',
            field=models.TextField(blank=True),
        ),
    ]
