# Generated by Django 2.1.5 on 2019-01-28 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190127_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='music.Album'),
        ),
    ]
